<?php


namespace Payments\KnetPayment;
//use Payments\KnetPayment\Knet;
require_once "Knet.php";

/********** for live start=========== */
//public $TranportalId='208901';
//public $Password='FG3QrDdh';
//public $ResourceKey='Y10ZE99MG74Y9YG8';
/********** for Test start=========== */
/*public $TranportalId='195501';//for test
public $Password='195501pg';
public $ResourceKey='57Q2Y6B9Y41TRY7K';
*/
class TestKnet extends Knet
{
    public function __construct($config = array())
    {
        parent::__construct($config);
    }

    public function run(){
        return $this->request();
    }

    public function beforeValidate()
    {
        parent::beforeValidate(); // TODO: Change the autogenerated stub
        return true;
    }
}


$testknet = new TestKnet(["is_test"=>true,"tranportal_id"=>195501,"password"=>"195501pg","resource_key"=>"57Q2Y6B9Y41TRY7K"]);

echo "<pre>";
$testknet->amount = 1;
$testknet->response_url = "http://localhost:8888/knet-payment/src/result.php";
$testknet->error_url = "http://localhost:8888/knet-payment/src/result.php";

//print_r($testknet->run());
/**
 * Array
(
[status] => 1
[data] => Array
(
[url] => https://kpaytest.com.kw/kpg/PaymentHTTP.htm?param=paymentInit&trandata=f5b4a90b68c2bcc2e0476dc5274fd30450b22ba72950a2461e78367af401e0ab91f7db4eae403a59f3e072a6c53fe042dfa315efc8562ebb25b482f486cfb8e0584a9a40d1f5644d255da8438d694f966187c508b58f8ef2c9c97e91f6cd2f0ce67287d9b256d12e7e0b311d5733b0ffe6b66f4e53457a655974b1e96ac24978bca632ae920248b7480c1e1022c8b9e3f4e39ab22aef5fd8187da663c5c5fa3b9826b2d2cfc2bdddec8435525efe482a2a0123742b049cc45d064c05a6b309abf8d8af3bd0a0f7b271a5e19c218fd18d636c6b1a8d2b42b0512ce464b5e10ad9b88ecbe8ef226735e3fb68285cf39351f44d5de271a7e28df1adb669edd88eb5&tranportalId=195501&responseURL=http://localhost:8888/knet-payment/src/result.php&errorURL=http://localhost:8888/knet-payment/src/result.php
[paymentid] => 16245825122539
)

[errors] =>
)

 */